### ISSUE TITLE
Great terraform video

### ISSUE THREAD

**Issue by mercarey** [ChristianLempa/videos#21]
https://www.youtube.com/watch?v=fEIIxZUf4co

To be honest, I felt like thinking "What is this all aiming towards??" throughout a large part of the video! [😅](https://emojipedia.org/grinning-face-with-sweat/)

But then it all came together right at the end, specifically 29:18 - 29:38 (https://www.youtube.com/watch?v=fEIIxZUf4co&t=1759s)

"And you can this... this is now working. We are logged into our server.
"This probably took like, hmm, a few seconds to deploy this cloud instance? So this is pretty cool. You can see what you can do with that; Terraform is very, very powerful to dynamically provision infrastructure this way."

Those 20 seconds copied right at the start of the video as like a "teaser" (maybe you are not into that style) would be very helpful, tutorial-wise. It lets me know what your goal is and, from your genuine reaction of being pleasantly surprised, how worthwhile my attention should be to the subject.

Great video, thanks for the content. I will watch more and share.

**Comment by ChristianLempa** [comment]
Thank you so much for the feedback, and sorry for the late response :( I had a hard time keeping up with all the comments, github issues and DMs.
