### ISSUE TITLE
Docker problem 

### ISSUE THREAD

**Issue by emmu123** [ChristianLempa/videos#28]
![IMG_20221122_174005](https://user-images.githubusercontent.com/89377181/203310819-22335aa7-c1b7-4d15-939c-5e2be4eff887.jpg)
How solve this pls help me

**Comment by ChristianLempa** [comment]
Seems like an issue in your compose file, can you post it?

**Comment by jboucher614** [comment]
Having this issue with the nextcloud [nextcloud](https://github.com/christianlempa/videos/blob/main/nextcloud-tutorial/docker-compose.yml) docker compose, too

Thank you for your excellent videos and text tutorials btw!

**Comment by ChristianLempa** [comment]
@jboucher614 can you post your compose file, please? we need to check the docs in here.

**Comment by ChristianLempa** [comment]
Thanks for your message ;) I sent you a reply on GitHub.

On 2. Dec 2022, at 02:33, Jimmy Boucher ***@***.***> wrote:

Having this issue with the nextcloud nextcloud docker compose, too Thank you for your excellent videos and text tutorials btw! — Reply to this email directly, view it on GitHub, or unsubscribe. You ar
Caution! This message was sent from outside your organization.
sophospsmartbannerend


Having this issue with the nextcloud nextcloud<https://github.com/christianlempa/videos/blob/main/nextcloud-tutorial/docker-compose.yml> docker compose, too

Thank you for your excellent videos and text tutorials btw!

**Comment by jboucher614** [comment]
I was just using the Nextcloud .yml file linked, here's the text:
`version: "3"
volumes:
  nextcloud-data:
  nextcloud-db:
  npm-data:
  npm-ssl:
  npm-db:

networks:
  frontend:
    # add this if the network is already existing!
    # external: true
  backend:

services:
  nextcloud-app:
    image: nextcloud
    restart: always
    volumes:
      - nextcloud-data:/var/www/html
    environment:
      - MYSQL_PASSWORD=replace-with-secure-password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
    networks:
      - frontend
      - backend

  nextcloud-db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=replace-with-secure-password
      - MYSQL_PASSWORD=replace-with-secure-password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - backend

  npm-app:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      - DB_MYSQL_HOST=npm-db
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_USER=npm
      - DB_MYSQL_PASSWORD=replace-with-secure-password
      - DB_MYSQL_NAME=npm
    volumes:
      - npm-data:/data
      - npm-ssl:/etc/letsencrypt
    networks:
      - frontend
      - backend

  npm-db:
    image: jc21/mariadb-aria:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=replace-with-secure-password
      - MYSQL_DATABASE=npm
      - MYSQL_USER=npm
      - MYSQL_PASSWORD=replace-with-secure-password
    volumes:
      - npm-db:/var/lib/mysql
    networks:
      - backend`

I tried copy-pasting it into Portainer and nano but had syntax issues each time. I pasted the whole file into yamlchecker.com and got this:

can not read a block mapping entry; a multiline key may not be an implicit key (13:10)

 10 |   frontend:
 11 |     # add this if the network is already ...
 12 |     # external: true
 13 |   backend:
---------------^
 14 | 
 15 | services:

If I delete the commented lines, that error goes away but this one starts:


can not read a block mapping entry; a multiline key may not be an implicit key (17:12)

 14 |   nextcloud-app:
 15 |     image: nextcloud
 16 |     restart: always
 17 |     volumes:
-----------------^
 18 |       - nextcloud-data:/var/www/html
 19 |     environment:


Possibly it's something to do with copying and pasting? I've reviewed the formatting a bunch and can't figure out what's wrong, but I'm a YAML noob.
