### ISSUE TITLE
Existing NPM 

### ISSUE THREAD

**Issue by Neu-Bob** [ChristianLempa/videos#32]
Thanks for your great videos.  I already have NPM running, you mention this scenario briefly but never talk about ports that have to be setup on the nextcloud-app... am I missing something?

**Comment by ChristianLempa** [comment]
Thanks for your feedback! Can you explain in further detail, what's your setup and what you're trying to achieve?

**Comment by Neu-Bob** [comment]
My apologies for the brevity.  

I am currently running nginx proxy manager and would like to get nextcloud running.  This video seemed to touch on my setup but didn't come back to it.  I have tried nextcloud-aio but it's got too many features, I'm simply trying to replace dropbox/google drive  As a bonus I run all of my containers from a dedicated ubuntu server and try to store all my data on a Synology with NFS shares, either in the container or as a fixed share from the ubuntu server.  I think in the video what may be missing is ports?  If you're not installing NPM I would assume you have to expose the ports directly on the NextCloud container, but not sure.

**Comment by ChristianLempa** [comment]
That's right, if you're not running NPM you will have to expose the ports manually. Just to clarify, is there something that's missing in the documentation, or do you need help with setting it up?

**Comment by Neu-Bob** [comment]
That just wasn't clear in the video.  I can go back to the next cloud documentation
