### ISSUE TITLE
; missing

### ISSUE THREAD

**Issue by stundenblume** [ChristianLempa/videos#36]
in the [bin9 docs](https://github.com/ChristianLempa/videos/tree/main/bind9-docker#create-the-main-config-file) in named.conf is a ";" after "192.168.0.0/24" missing.

```
acl internal {
  192.168.0.0/24;
};
```

By the way: Thank you for your excellent videos and proper documentation!

**Comment by ChristianLempa** [comment]
Good one! Thank you :)
