### ISSUE TITLE
question: kubernetes at home

### ISSUE THREAD

**Issue by phanirithvij** [ChristianLempa/videos#37]
In your HA k3s video, there is an ASCII diagram in a markdown file at [08:36](https://youtu.be/UdjhFLV1yt8?t=516) i.e. [image](https://user-images.githubusercontent.com/29627898/211880272-e1c69299-8695-444e-98df-504a5b2fa5fa.png)

May I know what tools you are using to create and show this ASCII diagram in the terminal?

**Comment by ChristianLempa** [comment]
I was using asciiflow to generate that, however I'm now using a better tool for visualizing, as the ascii diagrams are hard to edit.

**Comment by ChristianLempa** [comment]
I was using asciiflow.com<http://asciiflow.com> for this.

On 11. Jan 2023, at 18:51, Phani Rithvij ***@***.***> wrote:

In your HA k3s video, there is an ASCII diagram in a markdown file at 08:36 i.e. image May I know what tools you are using to create and show this ASCII diagram in the terminal? — Reply to this email
Caution! This message was sent from outside your organization.
sophospsmartbannerend


In your HA k3s video, there is an ASCII diagram in a markdown file at 08:36<https://youtu.be/UdjhFLV1yt8?t=516> i.e. image<https://user-images.githubusercontent.com/29627898/211880272-e1c69299-8695-444e-98df-504a5b2fa5fa.png>

May I know what tools you are using to create and show this ASCII diagram in the terminal?
