### ISSUE TITLE
videos/truenasscale-traefik

### ISSUE THREAD

**Issue by VallicMagnus** [ChristianLempa/videos#50]
After a recent update to the TrueCharts Traefik application this method no longer works.

https://github.com/truecharts/charts/pull/9116

The ingressClass* now doesn't work to pass the certificate the way the video explains. This apparently was not intended to work this way in the first place and a breaking update was made after the breaking change update. 

It would be great to have an amendment in the video or an update on how to restore functionality.

**Comment by ChristianLempa** [comment]
Thanks for letting me know, I will revisit in the next days and decide what to do with it.

**Comment by VallicMagnus** [comment]
Actually, an update on this, I think one small change just needs to be made. Completely reinstall Traefik without IngressClass and IsDefaultClass checked. Then For existing installs you'd go uncheck all the ingress class settings for all current charts. After you've done that and let all the charts deploy, go back and redeploy each app with the ingress settings checked.

I think on any new installs all that has to be done is leave IngressClass and IsDefaultClass unchecked. So really minor fix for anyone coming in fresh and just a bit of fiddling with settings on multiple charts for existing users.

See the attached image from the TrueCharts discord, that's how I figured this out.

I think that this method might stop working again in the future unfortunately since the devs seen keen on removing the use of local certificates for charts at least that's what I've gathered.

It would be really cool to get a video on something like cert-manager, this could be a great alternative if this method stops working.

I really appreciate the videos, much more coherint than others on the platform for complicated tasks like this.

I wish you all the best,

Keylon De Lancey



________________________________

**Comment by ChristianLempa** [comment]
I've done some research on my end and it seems the TrueCharts implementation of Traefik is broken, that's why using IngressClasses doesn't work as expected in Traefik.

Yet, I haven't got an update from TrueCharts on this, whether they're willing to fix this in the near future or not.

I'm currently not very excited about making any new videos on this, to be honest...
