### ISSUE TITLE
ansible-semaphore

### ISSUE THREAD

**Issue by v-adityajoshi** [ChristianLempa/videos#53]
Throwing following error while configuring using example docker-compose.yaml file.

```
ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for services: 'mysql'
Unsupported config option for volumes: 'semaphore-mysql'
```

**Comment by Mcamin** [comment]
@v-adityajoshi 
Try setting the compose file version to 3.8 or 3.7 and make sure you configured the mapping properly
version: "3.8"
